### тест сокращателя
POST /
Host: localhost:8080
Content-Type: text/plain

http://example.com/very/long/url

### Возвращение ссылки (значение нужно менять)
# @no-redirect
GET /GDNEYi HTTP/1.1
Host: localhost:8080
Content-Type: text/plain

### json тест
POST /api/shorten
Host: localhost:8080
Content-Type: application/json

{
  "url": "http://example.com/very/very/long/url/2"
}

### gzip тест
POST http://localhost:8080/api/shorten
Accept-Encoding: gzip
Content-Type: application/json

{
  "url": "https://practicum.yandex.ru/is/2?easy"
}

### Batch insert test
POST /api/shorten/batch
host: localhost:8080
Content-Type: application/json

[
  {
    "correlation_id": "1",
    "original_url": "https://practicum.yandex.ru/11"
  },
  {
    "correlation_id": "2",
    "original_url": "https://practicum.yandex.ru/22"
  },
  {
    "correlation_id": "3a",
    "original_url": "https://practicum.yandex.ru/33"
  }
]